services:
  - type: web
    name: test-webhook-endpoint
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: VERIFY_TOKEN
        sync: false
